apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messages
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: dapr-redis.default.svc.cluster.local:6379
  - name: redisPassword
    value: ""