apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messages
  namespace: default
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: daprdemo-secret
        key: servicebus-connectionString