apiVersion: v1
kind: Service
metadata:
  name: daprdemo-auditsvc
  labels:
    app.kubernetes.io/name: auditsvc
    app.kubernetes.io/part-of: daprdemo
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: daprdemo-auditsvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daprdemo-auditsvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daprdemo-auditsvc
  template:
    metadata:
      labels:
        app: daprdemo-auditsvc
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "daprdemo-auditsvc"
        dapr.io/app-port: "80"
    spec:
      containers:
      - name: daprdemo-auditsvc
        image: heavenwing/daprdemo-auditsvc:buildx-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80