apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messages
  namespace: default
spec:
  type: pubsub.kafka
  version: v1
  metadata:
      # Kafka broker connection setting
    - name: brokers
      value: "dapr-kafka.default.svc.cluster.local:9092"
