apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.memcached
  version: v1
  metadata:
  - name: hosts
    value: "dapr-memcached.default.svc.cluster.local:11211"